### ISSUE TITLE
大佬能否开发linux版本的

### ISSUE THREAD

**Issue by hu-hamster** [LYshiying/JNU-clock_in#2]

**Comment by shirumesu** [comment]
你好！
不好意思现在才看到你的issue，这个程序是使用selenium去进行模拟的，linux一样可以运行，可以搜索一下ubuntu 安装 selenium这样的字眼去看看，安装chrome浏览器然后下载对应的chromedriver就可以了
搜了下感觉这个应该没什么问题，可以试试 https://shenxiaobing.com/post/2021/selenium-webdriver-on-linux-ubuntu/ 不过这个文章后面的Webdriver options篇可以无视

已经进行了版本更新！请在程序根目录使用`git pull`更新 然后可以使用`python3 ./main.py --chrome-path /path/to/chromedriver`指定chromedriver路径
目前我知道的是树莓派的aarch64的cpu几乎没法使用selenium，安装非常麻烦，但如果是普通云服务器或者自己电脑应该不存在这个问题

**Comment by hu-hamster** [comment]
好的，谢谢您
