### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by DIOenNI** [LYshiying/JNU-clock_in#5]
你好，
其实我一直都遇到这个error：

```
raceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.config import Config
  File "F:\GitHub\JNU-clock_in_4_29\src\config.py", line 7, in <module>
    class Config:
  File "F:\GitHub\JNU-clock_in_4_29\src\config.py", line 76, in Config
    def get_user(self, Re: bool = False) -> list[str]:
TypeError: 'type' object is not subscriptable
```

但是之前我是在config.py中把：

`def get_user(self, Re: bool = False) -> list[str]:`

改成以下，来蒙混过关：

```
str_1 = []
def get_user(self, Re: bool = False) -> str_1:
```
但是这样改完之后每次运行程序后都要我输入邮箱之类的，然后我就把mail.py里面的注释掉了，勉强能跑，求解这个报错原因（总感觉发挥不出工具的完整实力）

使用环境是py3.7

**Comment by seraph0012** [comment]
list[str]这种写法在python>=3.9以后才有，3.9以下的话要写成List[str]或者就list不要指定元素类型

**Comment by shirumesu** [comment]
你好！

感谢楼上，问题确实是在这里……（因为我是新版本其实一直没留意这个问题…虽然知道有这个报错但从来没去定位过…）

刚才已经更新修复了，请用`git pull`更新一下！

**Comment by DIOenNI** [comment]
> list[str]这种写法在python>=3.9以后才有，3.9以下的话要写成List[str]或者就list不要指定元素类型

感谢指点

**Comment by harrishan123** [comment]
如果不是版本问题呢，我是试了3.10喝3.11都是一样的报错，请问怎么办
