### ISSUE TITLE
滑块破解功能

### ISSUE THREAD

**Issue by seraph0012** [LYshiying/JNU-clock_in#6]
1.滑块距离计算算法改进
小小的测试了一下，滑块验证图片有两种，一种是拼图的地方变暗，一种是拼图的地方变亮，目前的程序使用的算法在变亮的情况下都能成功计算出距离，但变暗的情况下失败率是100%；图像处理这块要自己尝试各种算法调试参数挺麻烦的，我找到一个[现成的算法](https://github.com/peduajo/geetest-slice-captcha-solver)，经过测试变亮变暗都能完美计算出恰当的距离，基本上每次都能一次性完成滑块验证，打卡效率大大提高

2.webdriver防检测
目前程序里是有这样一行代码：
```
self.driver.execute_cdp_cmd(
            'Page.addScriptToEvaluateOnNewDocument',
            {
                'source': '''Object.defineProperty(navigator, 'webdriver', {
                    get: () => undefined
                })'''
            },
        )
```
但其实这个没啥用，因为webdriver是定义在Navigator.prototype里而不是navigator里，通过
`Object.getOwnPropertyDescriptor(Navigator.prototype, 'webdriver').get.apply(navigator)`
还是可以检测出来，会返回true。

经过测试，可以在ChromeOptions里加入--disable-blink-features=AutomationControlled来隐藏webdriver信息，使用这个flag之后上面的代码会返回false，虽然说既然本来的代码没用那说明根本就没有检测webdriver，加不加这些也就无所谓了。

**Comment by shirumesu** [comment]
你好！

## 1.滑块距离计算算法改进

感谢分享！刚才试了一下确实基本上都能计算出来，已经在新版本替换掉原来的了

## 2.webdriver防检测

说实话这段代码也是我网上抄的(reradme.md 感谢中的第三篇文章)，那时候我的JavaScript基本上只有最基本的计算的能力，完全没到浏览器操作的水平，直到前几天我才开始正式学js。  
但这段代码是起效的，曾经有一段时间网站更新了脚本监测机制，因为navigator.webdriver为true因此滑条验证就算完全对上了都会失败，在加入这段代码后可以正常打卡了  
测试了一下之后发现确实是已经取消这个监测机制了，就算没有这几行也能正常打卡。所以新版本也顺手注释掉了…
